# Makefile for Darklands
# C++ project using SDL graphics library

CXX = g++
CXXFLAGS = -std=c++11 -Wall -O2
CPPFLAGS = -I. -Ilibjgame \
	-Ilibjgame/graphics -Ilibjgame/audio \
	-Ilibjgame/support -Ilibjgame/timers \
	-Ilibjgame/streams

# SDL flags
SDL_CFLAGS := $(shell pkg-config --cflags sdl2)
SDL_LIBS := $(shell pkg-config --libs sdl2)

# Source files
SOURCES = darklands.cpp Catalog.cpp CityFile.cpp CityLabels.cpp FontFile.cpp GameData.cpp LocationFile.cpp MapFile.cpp MapViewer.cpp Palette.cpp PICImage.cpp TextSupport.cpp WorldMap.cpp
OBJECTS = $(SOURCES:.cpp=.o)
DEPS = $(SOURCES:.cpp=.d)
TARGET = darklands

# Dependencies from libjgame
LIBJGAME_DIR = libjgame
LIBJGAME_LIB = $(LIBJGAME_DIR)/lib/libjgame.a

# Final target
EXECUTABLE = $(TARGET)

.PHONY: all clean rebuild libjgame help

all: $(LIBJGAME_LIB) $(EXECUTABLE)

# Build the libjgame submodule
$(LIBJGAME_LIB):
	$(MAKE) -C $(LIBJGAME_DIR)

# Compile main executable
$(EXECUTABLE): $(OBJECTS) $(LIBJGAME_LIB)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SDL_LIBS) -lz -L$(LIBJGAME_DIR)

# Compile object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(SDL_CFLAGS) -MMD -MP -c $< -o $@

# Header dependencies generated by -MMD
-include $(DEPS)

# Clean build artifacts
clean:
	rm -f $(OBJECTS) $(DEPS) $(EXECUTABLE)
	$(MAKE) -C $(LIBJGAME_DIR) clean

# Rebuild from scratch
rebuild: clean all

# Help target
help:
	@echo "Darklands - Makefile targets:"
	@echo "  make all       - Build the project (default)"
	@echo "  make clean     - Remove build artifacts"
	@echo "  make rebuild   - Clean and rebuild"
	@echo "  make help      - Show this help message"
