# Makefile for Darklands
# C++ project using SDL graphics library

CXX = g++
CXXFLAGS = -std=c++11 -Wall -O2
CPPFLAGS = -Isrc/formats -Isrc/game -Isrc/ui -Ilibjgame \
	-Ilibjgame/graphics -Ilibjgame/audio \
	-Ilibjgame/support -Ilibjgame/timers \
	-Ilibjgame/streams

# SDL flags
SDL_CFLAGS := $(shell pkg-config --cflags sdl2)
SDL_LIBS := $(shell pkg-config --libs sdl2)

# Source files: src/darklands.cpp and every .cpp under src/*/
SOURCES = $(wildcard src/*.cpp src/*/*.cpp)
OBJDIR = obj
OBJECTS = $(SOURCES:src/%.cpp=$(OBJDIR)/%.o)
DEPS = $(OBJECTS:.o=.d)
TARGET = darklands

# Version: from git (tag, or tag-N-gHASH), or `make VERSION=x.y.z` when
# building outside a checkout. Compiled into the program (--version).
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo unknown)
VERSION_SRC = $(OBJDIR)/Version.cpp
VERSION_OBJ = $(OBJDIR)/Version.o

# Dependencies from libjgame
LIBJGAME_DIR = libjgame
LIBJGAME_LIB = $(LIBJGAME_DIR)/lib/libjgame.a

# Final target
EXECUTABLE = $(TARGET)

.PHONY: all clean rebuild libjgame help dist FORCE

all: $(LIBJGAME_LIB) $(EXECUTABLE)

# Build the libjgame submodule
$(LIBJGAME_LIB):
	$(MAKE) -C $(LIBJGAME_DIR)

# Compile main executable
$(EXECUTABLE): $(OBJECTS) $(VERSION_OBJ) $(LIBJGAME_LIB)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SDL_LIBS) -lz -L$(LIBJGAME_DIR)

# Compile object files
$(OBJDIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(SDL_CFLAGS) -MMD -MP -c $< -o $@

# The version string, regenerated only when it changes
$(VERSION_SRC): FORCE
	@mkdir -p $(OBJDIR)
	@echo 'extern const char* const kVersion; const char* const kVersion = "$(VERSION)";' > $@.tmp
	@cmp -s $@.tmp $@ && rm $@.tmp || mv $@.tmp $@

$(VERSION_OBJ): $(VERSION_SRC)
	$(CXX) $(CXXFLAGS) -c $< -o $@

FORCE:

# Release package: dist/darklands-<version>-<os>-<arch>.tar.gz
PLATFORM := $(shell uname -s | tr A-Z a-z)-$(shell uname -m)
DISTNAME = darklands-$(VERSION)-$(PLATFORM)
dist: all
	rm -rf dist/$(DISTNAME)
	mkdir -p dist/$(DISTNAME)
	cp $(EXECUTABLE) README.md dist/$(DISTNAME)/
	cp -r docs dist/$(DISTNAME)/docs
	@cp LICENSE* dist/$(DISTNAME)/ 2>/dev/null || true
	tar -C dist -czf dist/$(DISTNAME).tar.gz $(DISTNAME)
	rm -rf dist/$(DISTNAME)
	@echo "dist/$(DISTNAME).tar.gz"

# Header dependencies generated by -MMD
-include $(DEPS)

# Clean build artifacts
clean:
	rm -rf $(OBJDIR) $(EXECUTABLE) dist
	$(MAKE) -C $(LIBJGAME_DIR) clean

# Rebuild from scratch
rebuild: clean all

# Help target
help:
	@echo "Darklands - Makefile targets:"
	@echo "  make all       - Build the project (default)"
	@echo "  make clean     - Remove build artifacts"
	@echo "  make rebuild   - Clean and rebuild"
	@echo "  make dist      - Build the release package in dist/"
	@echo "  make help      - Show this help message"
